### ISSUE TITLE
§ instead of Ś

### ISSUE THREAD

**Issue by Digharatta** [bdhrs/pali-sanksrit-keyboard-for-linux#2]
Hello,

Thank you for your work.

Would you please replace § with Ś on the US keyboard?

Thank you in advance!

**Comment by bdhrs** [comment]
It's very easy to customize the layout to suit your personal preferences.  For example, 

- Navigatre to the `/usr/share/X11/xkb/symbols` directory

- Open the keyboard layout with `sudo gedit us` or your preferred text editor. 

- Find `U00A7` (§) and replace with your preferred `U015A` (Ś).

- Save, close and smile.
